spring.application.name=VendingMachineWeb

spring.datasource.url=jdbc:mysql://localhost:3306/vending_machine?useSSL=false&serverTimezone=Asia/Tokyo&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.address=0.0.0.0
server.port=8080